* Resources
https://tecosaur.github.io/emacs-config/config.html
https://dotdoom.rgoswami.me/config
* Doom Keybinds
Set the leader to spacemacs
#+begin_src emacs-lisp
(setq doom-localleader-key ",")
#+end_src
* Doom
There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:

#+begin_src emacs-lisp
(setq doom-theme 'modus-vivendi)

#+end_src

This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src emacs-lisp
(setq display-line-numbers-type `relative)
#+end_src

#+begin_src emacs-lisp
(setq require-final-newline nil)
#+end_src

#+begin_src emacs-lisp
(setq shell-file-name (executable-find "bash"))
#+end_src
* Which Key
Set the whick key opening delay to  0.5 seconds
#+begin_src emacs-lisp
(setq which-key-idle-delay 0.5)
#+end_src

replace evil- in which-key entries to make em easier to read
#+begin_src emacs-lisp
(setq which-key-allow-multiple-replacements t)
(after! which-key
  (pushnew!
   which-key-replacement-alist
   '(("" . "\\`+?evil[-:]?\\(?:a-\\)?\\(.*\\)") . (nil . "◂\\1"))
   '(("\\`g s" . "\\`evilem--?motion-\\(.*\\)") . (nil . "◃\\1"))
   ))

#+end_src
* Org Mode
Set the directory
#+begin_src emacs-lisp

(add-hook 'org-mode-hook 'turn-on-org-cdlatex)
(add-hook 'LaTeX-mode-hook 'turn-on-cdlatex)
(add-hook 'org-mode-hook 'org-latex-preview)

(defun enable-word-processor-minor-modes ()
  (setq line-spacing 0.15)
  ;;(pixel-scroll-precision-mode)
  (smartparens-mode)
  (visual-line-mode))
;;  (add-hook 'window-size-change-functions 'org-image-resize)
(add-hook 'text-mode-hook 'enable-word-processor-minor-modes)
;;(add-hook 'org-mode-hook 'org-appear-mode)
(add-hook 'org-mode-hook 'org-roam-db-autosync-enable)
(add-hook 'org-mode-hook 'org-latex-preview-auto-mode)
(after! org
  (setq org-directory "~/notes/org-mode/")
  (setq org-roam-directory "~/notes/org-mode/")
  (setq org-habit-show-habits-only-for-today nil)
  (setq org-agenda-files (directory-files-recursively "~/notes/org-mode/" "\\.org$"))
  (setq org-pretty-entities t)
  (setq org-hide-emphasis-markers t)
  (setq org-startup-folded `content)
  (setq org-ellipsis "  ") ;; folding symbol
  )

#+end_src

** Org Writeroom
Setting the variable fonts
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Iosevka Nerd Font Mono")
      doom-variable-pitch-font (font-spec :family "Vollkorn"))
#+end_src

#+begin_src emacs-lisp
(setq +zen-text-scale 1)
(setq writeroom-width 0.8)
(add-hook 'org-mode-hook 'writeroom-mode)
#+end_src
** Run buffers in org-mode by default:
#+begin_src emacs-lisp
(setq-default major-mode 'org-mode)
#+end_src
** Org Keybinds

I want the following keybinds to be added that i've noticed
The *insert* maps
The *text* maps
Comment lines
ctrl c ctrl c
copy and clipboard.
display org roam tags in node search
Other stuff- daemon mode,
smartparens equivalency (default +smartparens under doom config is NOT all you need, bind sp-sexp-up to tab)
** Org Appear
#+begin_src emacs-lisp
(setq org-appear-autolinks t)
(setq org-appear-autoentities t)
(setq org-appear-autosubmarkers t)
(setq org-appear-autokeywords t)
(setq org-appear-inside-latex t)

;; It's cool to have appear only work in insert mode, gonna leave in automatic for now
;; (setq org-appear-trigger 'manual)
;; (add-hook 'org-mode-hook (lambda ()
;;                           (add-hook 'evil-insert-state-entry-hook
;;                                     #'org-appear-manual-start
;;                                     nil
;;                                     t)
;;                           (add-hook 'evil-insert-state-exit-hook
;;                                     #'org-appear-manual-stop
;;                                     nil
;;                                     t)))
#+end_src
** Be able to search folded headings in org mode
**  Org roam
* Projectile
#+begin_src emacs-lisp
  (setq projectile-cache-file (concat doom-cache-dir "projectile.cache")
        projectile-enable-caching (not noninteractive)
        projectile-indexing-method (if IS-WINDOWS 'native 'alien)
        projectile-known-projects-file (concat doom-cache-dir "projectile.projects")
        projectile-require-project-root nil
        projectile-globally-ignored-files '(".DS_Store" "Icon
" "TAGS")
        projectile-globally-ignored-file-suffixes '(".elc" ".pyc" ".o")
        projectile-ignored-projects '("~/" "/tmp"))
#+end_src
* Transparency
Setting 80% transparency
#+begin_src emacs-lisp
(set-frame-parameter nil 'alpha-background 80)
#+end_src

* LSP
Set up ccls
#+begin_src emacs-lisp
(set-eglot-client! 'cc-mode '("clangd" "-j=3" "--clang-tidy" "--compile-commands-dir=cmake-build-debug"))
#+end_src
lens update is very slow
#+begin_src emacs-lisp
  (setq lsp-lens-enable nil)
#+end_src

#+begin_src emacs-lisp
(after! cc-mode
  (add-hook! 'c++-mode-hook
             (defun +cc-comment-style-to-block ()
               "use block comments instead of line comments"
               (c-toggle-comment-style 1))))
#+end_src

#+begin_src emacs-lisp
(after! cc-mode
  (setq c-max-one-liner-length 150))
#+end_src
